name: Build and Push Runner Image

on:
  pull_request:
    branches:
      - main
    paths:
      - "images/**"
      - "CHANGELOG.md" # to also trigger on release-please managed PRs for upcoming releases

  push:
    tags:
      - "*"

  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"
      checks: "write"
      packages: "write"
      security-events: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@18ce135bb5112fa8ce4ed6c17ab05699d7f3a5e0 # v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build image
        id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: images/ubuntu-24.04
          file: images/ubuntu-24.04/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          push: ${{ github.event_name != 'schedule' && github.event_name != 'workflow_dispatch' }}

      - name: Scan image with grype
        id: scan
        uses: anchore/scan-action@be7a22da4f22dde446c4c4c099887ff5b256526c # v6
        with:
          image: ${{ steps.build.outputs.imageid }}
          fail-build: false

      - name: Upload scan results
        uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 # v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
          ref: ${{ github.ref_type == 'tag' && 'refs/heads/main' || github.ref }}
          sha: ${{ github.sha }}

      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
